spring.application.name=hbase-demo
# ---------------------- Kafka ???? ----------------------
# Kafka ????????
spring.kafka.bootstrap-servers=192.168.56.101:9092

# ---------------------- Kafka ????????2?? ----------------------
# ????????????
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
# ???1?? Kafka ?? String ?????? FastJSON ??????
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
# ???????1=??leader???????????????
spring.kafka.producer.acks=1
# ?????????3??
spring.kafka.producer.retries=3
# ???????16KB?????IO?
spring.kafka.producer.batch-size=16384
# ????????32MB?
spring.kafka.producer.buffer-memory=33554432

# ---------------------- Kafka ????????1?? ----------------------
# ????ID?WebSocket ?????????????
spring.kafka.consumer.group-id=movie-rating-websocket-group
# ?????????????
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# ???2?? Kafka ?? String ??????? FastJSON ??????
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# ?????????????????????
spring.kafka.consumer.auto-offset-reset=earliest
# ?????????????????????????
spring.kafka.consumer.enable-auto-commit=false
# ????????????????????
spring.kafka.consumer.max-poll-records=100

# ---------------------- ????????? ----------------------
# ??????????????????
spring.kafka.listener.ack-mode=MANUAL_IMMEDIATE
# ????????? Kafka ????????3??
spring.kafka.listener.concurrency=3